//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoderTemplate) DeepCopyInto(out *CoderTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoderTemplate.
func (in *CoderTemplate) DeepCopy() *CoderTemplate {
	if in == nil {
		return nil
	}
	out := new(CoderTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CoderTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoderTemplateList) DeepCopyInto(out *CoderTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CoderTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoderTemplateList.
func (in *CoderTemplateList) DeepCopy() *CoderTemplateList {
	if in == nil {
		return nil
	}
	out := new(CoderTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CoderTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoderTemplateSpec) DeepCopyInto(out *CoderTemplateSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoderTemplateSpec.
func (in *CoderTemplateSpec) DeepCopy() *CoderTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(CoderTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoderTemplateStatus) DeepCopyInto(out *CoderTemplateStatus) {
	*out = *in
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.AutoShutdown != nil {
		in, out := &in.AutoShutdown, &out.AutoShutdown
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoderTemplateStatus.
func (in *CoderTemplateStatus) DeepCopy() *CoderTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(CoderTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoderWorkspace) DeepCopyInto(out *CoderWorkspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoderWorkspace.
func (in *CoderWorkspace) DeepCopy() *CoderWorkspace {
	if in == nil {
		return nil
	}
	out := new(CoderWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CoderWorkspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoderWorkspaceList) DeepCopyInto(out *CoderWorkspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CoderWorkspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoderWorkspaceList.
func (in *CoderWorkspaceList) DeepCopy() *CoderWorkspaceList {
	if in == nil {
		return nil
	}
	out := new(CoderWorkspaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CoderWorkspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoderWorkspaceSpec) DeepCopyInto(out *CoderWorkspaceSpec) {
	*out = *in
	if in.TTLMillis != nil {
		in, out := &in.TTLMillis, &out.TTLMillis
		*out = new(int64)
		**out = **in
	}
	if in.AutostartSchedule != nil {
		in, out := &in.AutostartSchedule, &out.AutostartSchedule
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoderWorkspaceSpec.
func (in *CoderWorkspaceSpec) DeepCopy() *CoderWorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(CoderWorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoderWorkspaceStatus) DeepCopyInto(out *CoderWorkspaceStatus) {
	*out = *in
	if in.AutoShutdown != nil {
		in, out := &in.AutoShutdown, &out.AutoShutdown
		*out = (*in).DeepCopy()
	}
	if in.LastUsedAt != nil {
		in, out := &in.LastUsedAt, &out.LastUsedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoderWorkspaceStatus.
func (in *CoderWorkspaceStatus) DeepCopy() *CoderWorkspaceStatus {
	if in == nil {
		return nil
	}
	out := new(CoderWorkspaceStatus)
	in.DeepCopyInto(out)
	return out
}
