version: "2"

run:
  timeout: 5m
  modules-download-mode: vendor

linters:
  enable:
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - nilerr
    - revive

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
