project_name: coder-k8s

before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  - id: coder-k8s
    main: ./
    binary: coder-k8s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    files:
      - none*

dockers:
  - id: coder-k8s-image
    image_templates:
      - "ghcr.io/coder/coder-k8s:{{ .Version }}"
      - "ghcr.io/coder/coder-k8s:latest"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/coder/coder-k8s"
      - "--label=org.opencontainers.image.url=https://coder.github.io/coder-k8s/"
      - "--label=org.opencontainers.image.documentation=https://coder.github.io/coder-k8s/"
      - "--label=org.opencontainers.image.title=coder-k8s"
      - "--label=org.opencontainers.image.description=Kubernetes operator for Coder"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.vendor=Coder"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--label=org.opencontainers.image.authors=Coder"

changelog:
  use: github
