#!/usr/bin/env bash
set -euo pipefail

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# list_manifests <dir>: prints the sorted *.yaml file names in <dir>. The directory must not contain a
# kustomization.yaml, because README, docs, hack/kind-dev.sh and the E2E job apply it with `kubectl apply -f <dir>/`.
list_manifests() {
	local manifests_dir="${1:-}"

	if [[ -z "${manifests_dir}" || ! -d "${SCRIPT_ROOT}/${manifests_dir}" ]]; then
		echo "assertion failed: expected manifest directory at ${SCRIPT_ROOT}/${manifests_dir}" >&2
		exit 1
	fi
	if [[ -e "${SCRIPT_ROOT}/${manifests_dir}/kustomization.yaml" ]]; then
		echo "assertion failed: ${manifests_dir}/kustomization.yaml breaks kubectl apply -f ${manifests_dir}/" >&2
		exit 1
	fi

	local -a resource_files=()
	mapfile -t resource_files < <(
		find "${SCRIPT_ROOT}/${manifests_dir}" -maxdepth 1 -mindepth 1 -type f -name '*.yaml' -printf '%f\n' | sort
	)
	if [[ "${#resource_files[@]}" -eq 0 ]]; then
		echo "assertion failed: expected at least one manifest in ${SCRIPT_ROOT}/${manifests_dir}" >&2
		exit 1
	fi
	printf '%s\n' "${resource_files[@]}"
}

# RBAC manifests that only the aggregated API server needs; the controller-only install bundle leaves them out.
BUNDLE_EXCLUDED_RBAC=(auth-delegator-binding.yaml authentication-reader-binding.yaml)

# write_default_kustomization lists every generated CRD and RBAC file individually, so the install bundle
# picks up new files automatically without placing kustomization files in the directories above. The bundle
# installs the operator in controller mode only (config/default/controller-mode-patch.yaml).
write_default_kustomization() {
	local crd_list rbac_list excluded
	# Command substitution (not process substitution) so a failed assertion in list_manifests stops the script.
	crd_list="$(list_manifests "config/crd/bases")"
	rbac_list="$(list_manifests "config/rbac")"
	local -a crd_files=() rbac_files=()
	mapfile -t crd_files <<<"${crd_list}"
	mapfile -t rbac_files <<<"${rbac_list}"

	for excluded in "${BUNDLE_EXCLUDED_RBAC[@]}"; do
		if [[ ! -f "${SCRIPT_ROOT}/config/rbac/${excluded}" ]]; then
			echo "assertion failed: expected config/rbac/${excluded} (listed in BUNDLE_EXCLUDED_RBAC)" >&2
			exit 1
		fi
	done
	if [[ ! -f "${SCRIPT_ROOT}/config/default/controller-mode-patch.yaml" ]]; then
		echo "assertion failed: expected config/default/controller-mode-patch.yaml" >&2
		exit 1
	fi
	local -a bundle_rbac_files=()
	local rbac_file
	for rbac_file in "${rbac_files[@]}"; do
		[[ " ${BUNDLE_EXCLUDED_RBAC[*]} " == *" ${rbac_file} "* ]] || bundle_rbac_files+=("${rbac_file}")
	done

	{
		echo "# Generated by hack/update-manifests.sh (make manifests); do not edit."
		echo "apiVersion: kustomize.config.k8s.io/v1beta1"
		echo "kind: Kustomization"
		echo "resources:"
		echo "  - namespace-coder-system.yaml"
		printf '  - ../crd/bases/%s\n' "${crd_files[@]}"
		printf '  - ../rbac/%s\n' "${bundle_rbac_files[@]}"
		echo "  - ../../deploy/deployment.yaml"
		echo "patches:"
		echo "  - path: controller-mode-patch.yaml"
	} > "${SCRIPT_ROOT}/config/default/kustomization.yaml"
}

if [[ ! -d "${SCRIPT_ROOT}/api/v1alpha1" ]]; then
	echo "assertion failed: expected API package at ${SCRIPT_ROOT}/api/v1alpha1" >&2
	exit 1
fi

if [[ ! -d "${SCRIPT_ROOT}/internal/controller" ]]; then
	echo "assertion failed: expected controller package at ${SCRIPT_ROOT}/internal/controller" >&2
	exit 1
fi

cd "${SCRIPT_ROOT}"

# config/crd/bases/ is fully generated, and controller-gen never deletes CRDs of removed or renamed API types.
# Clear it first so a stale CRD cannot keep shipping in config/default and dist/install.yaml.
if [[ ! -d config/crd/bases ]]; then
	echo "assertion failed: expected CRD directory at ${SCRIPT_ROOT}/config/crd/bases" >&2
	exit 1
fi
find config/crd/bases -maxdepth 1 -mindepth 1 -type f -name '*.yaml' -delete
# config/rbac/ also holds hand-written manifests, so only its generated role.yaml is removed and must be recreated.
rm -f config/rbac/role.yaml

# Generate CRDs for operator-owned coder.com APIs only.
GOFLAGS=-mod=vendor go run ./vendor/sigs.k8s.io/controller-tools/cmd/controller-gen \
	crd:crdVersions=v1 \
	paths=./api/v1alpha1 \
	output:crd:artifacts:config=config/crd/bases

# Generate RBAC across the repo.
GOFLAGS=-mod=vendor go run ./vendor/sigs.k8s.io/controller-tools/cmd/controller-gen \
	rbac:roleName=manager-role \
	paths=./... \
	output:rbac:artifacts:config=config/rbac

if [[ ! -s config/rbac/role.yaml ]]; then
	echo "assertion failed: controller-gen did not write config/rbac/role.yaml" >&2
	exit 1
fi

write_default_kustomization
