{{- define "typeName" -}}
{{- $fieldType := . -}}
{{- if not $fieldType -}}
<unknown>
{{- else -}}
{{- $typeString := $fieldType.String -}}
{{- $typeString = trimPrefix "*" $typeString -}}
{{- $typeString = $typeString | replace "k8s.io/apimachinery/pkg/apis/meta/v1." "metav1." -}}
{{- $typeString -}}
{{- end -}}
{{- end -}}

{{- define "gvList" -}}
{{- $groupVersions := . -}}
{{- if ne (len $groupVersions) 1 -}}
{{ fail "expected exactly one group-version from --source-path" }}
{{- end -}}

{{- $kind := markdownTemplateValue "kind" -}}
{{- if eq $kind "" -}}
{{ fail "missing --template-value=kind=<Kind>" }}
{{- end -}}

{{- $goType := markdownTemplateValue "goType" -}}
{{- if eq $goType "" -}}
{{ fail "missing --template-value=goType=<path>" }}
{{- end -}}

{{- $scope := markdownTemplateValue "scope" -}}
{{- if eq $scope "" -}}
{{- $scope = "namespaced" -}}
{{- end -}}

{{- $gv := index $groupVersions 0 -}}
{{- $rootType := $gv.TypeForKind $kind -}}
{{- if not $rootType -}}
{{ fail (printf "kind %q not found in source tree" $kind) }}
{{- end -}}
{{- if not $rootType.GVK -}}
{{ fail (printf "kind %q is missing GVK metadata" $kind) }}
{{- end -}}

{{- $specMembers := list -}}
{{- $statusMembers := list -}}
{{- range $field := $rootType.Members -}}
{{- if eq $field.Name "spec" -}}
{{- $specMembers = $field.Type.Members -}}
{{- end -}}
{{- if eq $field.Name "status" -}}
{{- $statusMembers = $field.Type.Members -}}
{{- end -}}
{{- end -}}
{{- if eq (len $specMembers) 0 -}}
{{ fail (printf "expected kind %q to contain at least one spec field" $kind) }}
{{- end -}}
{{- if eq (len $statusMembers) 0 -}}
{{ fail (printf "expected kind %q to contain at least one status field" $kind) }}
{{- end -}}

<!-- Code generated by hack/update-reference-docs.sh using github.com/elastic/crd-ref-docs. DO NOT EDIT. -->

# `{{ $kind }}`

## API identity

- Group/version: `{{ $rootType.GVK.Group }}/{{ $rootType.GVK.Version }}`
- Kind: `{{ $rootType.GVK.Kind }}`
- Resource: `{{ printf "%ss" (lower $kind) }}`
- Scope: {{ $scope }}

## Spec

| Field | Type | Description |
| --- | --- | --- |
{{ range $member := $specMembers -}}
| `spec.{{ $member.Name }}` | `{{ template "typeName" $member.Type }}` | {{ markdownRenderFieldDoc $member.Doc }} |
{{- end }}

## Status

| Field | Type | Description |
| --- | --- | --- |
{{ range $member := $statusMembers -}}
| `status.{{ $member.Name }}` | `{{ template "typeName" $member.Type }}` | {{ markdownRenderFieldDoc $member.Doc }} |
{{- end }}

## Source

- Go type: `{{ $goType }}`
{{- $generatedCRD := markdownTemplateValue "generatedCRD" -}}
{{- if ne $generatedCRD "" }}
- Generated CRD: `{{ $generatedCRD }}`
{{- end }}
{{- $storage := markdownTemplateValue "storage" -}}
{{- if ne $storage "" }}
- Storage implementation: `{{ $storage }}`
{{- end }}
{{- $apiServiceManifest := markdownTemplateValue "apiServiceManifest" -}}
{{- if ne $apiServiceManifest "" }}
- APIService registration manifest: `{{ $apiServiceManifest }}`
{{- end }}
{{- end }}
