{{- define "typeName" -}}
{{- $fieldType := . -}}
{{- if not $fieldType -}}
<unknown>
{{- else -}}
{{- $typeString := $fieldType.String -}}
{{- $typeString = trimPrefix "*" $typeString -}}
{{- $typeString = $typeString | replace "k8s.io/apimachinery/pkg/apis/meta/v1." "metav1." -}}
{{- $typeString = $typeString | replace "k8s.io/api/core/v1." "corev1." -}}
{{- $typeString = $typeString | replace "github.com/coder/coder-k8s/api/v1alpha1." "" -}}
{{- $typeString = $typeString | replace "github.com/coder/coder-k8s/api/aggregation/v1alpha1." "" -}}
{{- $typeString -}}
{{- end -}}
{{- end -}}

{{- define "renderFields" -}}
{{- $fields := .fields -}}
{{- $depth := int .depth -}}
{{- $maxDepth := int .maxDepth -}}
{{- $treePrefix := .treePrefix -}}
{{- $fieldCount := len $fields -}}
{{- range $index, $field := $fields }}
{{- if not $field.Type }}{{ fail (printf "field %q is missing type information" $field.Name) }}{{- end }}
{{- $memberType := $field.Type -}}
{{- $members := $memberType.Members -}}
{{- $hasMembers := gt (len $members) 0 -}}
{{- $memberTypeString := $memberType.String -}}
{{- $isProjectLocal := contains "github.com/coder/coder-k8s/api/" $memberTypeString -}}
{{- $isLocalObjectRef := contains "k8s.io/api/core/v1.LocalObjectReference" $memberTypeString -}}
{{- $shouldExpand := and $hasMembers (lt $depth $maxDepth) (or $isProjectLocal $isLocalObjectRef) -}}
{{- $isLast := eq (add $index 1) $fieldCount -}}
{{- $branch := "" -}}
{{- if gt $depth 0 -}}
{{- if $isLast -}}
{{- $branch = "└─ " -}}
{{- else -}}
{{- $branch = "├─ " -}}
{{- end -}}
{{- end -}}
{{- $fieldDoc := markdownRenderFieldDoc $field.Doc -}}
{{- $fieldDoc = $fieldDoc | replace "<br />" " " -}}
{{- $fieldDoc = regexReplaceAll "(https?://[^[:space:]<]+)" $fieldDoc "[$1]($1)" -}}
| {{ $treePrefix }}{{ $branch }}`{{ $field.Name }}` | `{{ template "typeName" $memberType }}` | {{ $fieldDoc }} |
{{ $childPrefix := $treePrefix -}}
{{- if gt $depth 0 -}}
{{- if $isLast -}}
{{- $childPrefix = printf "%s&nbsp;&nbsp;&nbsp;" $treePrefix -}}
{{- else -}}
{{- $childPrefix = printf "%s│&nbsp;&nbsp;" $treePrefix -}}
{{- end -}}
{{- else -}}
{{- $childPrefix = "" -}}
{{- end -}}
{{ if $shouldExpand }}{{ template "renderFields" (dict "fields" $members "depth" (add $depth 1) "maxDepth" $maxDepth "treePrefix" $childPrefix) }}{{ end }}
{{- end -}}
{{- end -}}

{{- define "gvList" -}}
{{- $groupVersions := . -}}
{{- if ne (len $groupVersions) 1 -}}
{{ fail "expected exactly one group-version from --source-path" }}
{{- end -}}

{{- $kind := markdownTemplateValue "kind" -}}
{{- if eq $kind "" -}}
{{ fail "missing --template-value=kind=<Kind>" }}
{{- end -}}

{{- $goType := markdownTemplateValue "goType" -}}
{{- if eq $goType "" -}}
{{ fail "missing --template-value=goType=<path>" }}
{{- end -}}

{{- $scope := markdownTemplateValue "scope" -}}
{{- if eq $scope "" -}}
{{- $scope = "namespaced" -}}
{{- end -}}

{{- $resource := markdownTemplateValue "resource" -}}
{{- if eq $resource "" -}}
{{- $resource = printf "%ss" (lower $kind) -}}
{{- end -}}

{{- $gv := index $groupVersions 0 -}}
{{- $rootType := $gv.TypeForKind $kind -}}
{{- if not $rootType -}}
{{ fail (printf "kind %q not found in source tree" $kind) }}
{{- end -}}
{{- if not $rootType.GVK -}}
{{ fail (printf "kind %q is missing GVK metadata" $kind) }}
{{- end -}}

{{- $specMembers := list -}}
{{- $statusMembers := list -}}
{{- range $field := $rootType.Members -}}
{{- if eq $field.Name "spec" -}}
{{- $specMembers = $field.Type.Members -}}
{{- end -}}
{{- if eq $field.Name "status" -}}
{{- $statusMembers = $field.Type.Members -}}
{{- end -}}
{{- end -}}
{{- if eq (len $specMembers) 0 -}}
{{ fail (printf "expected kind %q to contain at least one spec field" $kind) }}
{{- end -}}
{{- if eq (len $statusMembers) 0 -}}
{{ fail (printf "expected kind %q to contain at least one status field" $kind) }}
{{- end -}}
{{- $maxFieldDepth := 3 -}}

<!-- Code generated by hack/update-reference-docs.sh using github.com/elastic/crd-ref-docs. DO NOT EDIT. -->

# `{{ $kind }}`

## API identity

- Group/version: `{{ $rootType.GVK.Group }}/{{ $rootType.GVK.Version }}`
- Kind: `{{ $rootType.GVK.Kind }}`
- Resource: `{{ $resource }}`
- Scope: {{ $scope }}

## Spec

| Field | Type | Description |
| --- | --- | --- |
{{ template "renderFields" (dict "fields" $specMembers "depth" 0 "maxDepth" $maxFieldDepth "treePrefix" "") }}
## Status

| Field | Type | Description |
| --- | --- | --- |
{{ template "renderFields" (dict "fields" $statusMembers "depth" 0 "maxDepth" $maxFieldDepth "treePrefix" "") }}
## Source

- Go type: `{{ $goType }}`
{{- $generatedCRD := markdownTemplateValue "generatedCRD" -}}
{{ if ne $generatedCRD "" }}
- Generated CRD: `{{ $generatedCRD }}`
{{ end }}
{{- $storage := markdownTemplateValue "storage" -}}
{{ if ne $storage "" }}
- Storage implementation: `{{ $storage }}`
{{ end }}
{{- $apiServiceManifest := markdownTemplateValue "apiServiceManifest" -}}
{{ if ne $apiServiceManifest "" }}
- APIService registration manifest: `{{ $apiServiceManifest }}`
{{ end }}
{{- end -}}
