apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-db
  namespace: coder
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: coder
      owner: coder
